project:
  type: website
  output-dir: docs

website:
  title: "OpenSourceGIS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Using_QGIS.qmd
      - GIS_With_Python.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



